### ISSUE TITLE
Sharing iP code quality feedback [for @belligerentbeagle]

### ISSUE THREAD

**Issue by soc-se-script** [belligerentbeagle/ip#3]
@belligerentbeagle We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/service/Storage.java` lines `13-13`](https://github.com/belligerentbeagle/ip/blob/5d176f3c2b11bc82c2a819587d3c8ea742401f6a/src/main/java/service/Storage.java#L13..L13):

```java

    //private service.TaskList taskList;

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `19-22`](https://github.com/belligerentbeagle/ip/blob/5d176f3c2b11bc82c2a819587d3c8ea742401f6a/src/main/java/duke/Duke.java#L19..L22):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/duke/Duke.java` lines `106-109`](https://github.com/belligerentbeagle/ip/blob/5d176f3c2b11bc82c2a819587d3c8ea742401f6a/src/main/java/duke/Duke.java#L106..L109):

```java

    /**
     * With a Duke object, .run() is the main entry point of the program, running all its processes.
     *
     */

```

Example from [`src/main/java/model/Deadline.java` lines `38-41`](https://github.com/belligerentbeagle/ip/blob/5d176f3c2b11bc82c2a819587d3c8ea742401f6a/src/main/java/model/Deadline.java#L38..L41):

```java

    /**
     * Used to obtain the string in the format that the task would be saved in.
     * @return String representation of the deadline that is savable.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

possible problems in commit [`43a7f22`](https://github.com/belligerentbeagle/ip/commit/43a7f22d4b976644f4570aaf0312f804a9867abb):

```

Improve code quality further.

Added a new class 'TaskManager' to effectively process commands. The entirety of its logic was previously in Duke, which made Duke extremely lengthy. This also allowed for method refactoring, making the code follow SLAP closer.


```

* Subject line should not end with a period
* body not wrapped at 72 characters: e.g., `Added a new class 'TaskManager' to effectively process commands. The entirety of its logic was previously in Duke, which made Duke extremely lengthy. This also allowed for method refactoring, making the code follow SLAP closer.`
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (do not modify past commit messages as doing so will change the commit timestamp that we used to detect your commit timings).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by belligerentbeagle** [comment]
Fixed these problems
